### ISSUE TITLE
sh_dynamic.lua:196: attempt to call method 'GetDimensions'

### ISSUE THREAD

**Issue by thirteen-io** [MattJeanes/Safe-Space#12]
Hey Matt, Nice work on the addon so far.

I've been getting this on both the github and workshop version on my server.

```
[ERROR] addons/safe-space/lua/safespace/sh_dynamic.lua:196: attempt to call method 'GetDimensions' (a nil value)
  1. GetLighting - addons/safe-space/lua/safespace/sh_dynamic.lua:196
   2. CustomDrawModel - addons/safe-space/lua/safespace/sh_dynamic.lua:305
    3. Draw - addons/doors/lua/entities/gmod_door_exterior/cl_init.lua:18
     4. unknown - gamemodes/base/entities/entities/base_anim.lua:50
```

Huge thanks for the addon! :smile:

**Edit:**
Just to confirm, that error is clientside.

**Comment by ICEconchy** [comment]
I'm getting this as well, looks like a conflict between Doors and safe space?

**Comment by MattJeanes** [comment]
I've been getting this a couple times too. Safe Space requires Doors, they definitely don't conflict. I'll have a look into this error but it's hard to reproduce - if anyone has reliable steps to create that error let me know!

**Comment by ICEconchy** [comment]
That is why the error is a bit strange?

**Comment by thirteen-io** [comment]
Hey Matt the problem happens seemingly every time on my server. If you want to add me on steam I'm happy to give you rcon, luadev or whatever info you need to help debug it. I'd love to see this working.

http://steamcommunity.com/id/_thirteen_

I will take some time tonight to look through and see if I can narrow the issue down further on my box.

I have noticed that the properties that's available on my single player game (where you set scale) isn't there on the server maybe this is related?

**Comment by MattJeanes** [comment]
@thirteen-io is your server's version up to date?
