### ISSUE TITLE
Error in Serverconsole when trying to create a safespace

### ISSUE THREAD

**Issue by GerhardP99** [MattJeanes/Safe-Space#25]
ERROR: Trying to derive entity gmod_safespace from non existant entity gmod_door_exterior!
Error: Tried to make a SENT (gmod_safespace) but it didn't have a 'Type' key!

**Comment by AmyJeanes** [comment]
Do you have the [Doors](https://github.com/MattJeanes/Doors) addon installed?

If you do, you've got too many addons loaded in gmod and it starts to fall apart and not load stuff properly. Try disabling all addons except for Safe Space and Doors and see if that works. Not a permanent solution of course, but it lets you know if too many addons is the issue.

**Comment by GerhardP99** [comment]
Oh, I dont have that addon didnt see that it is a requirement since I have uploaded the addon directly to the server, oops :D
